name: news
description: "A Flutter app for browsing and liking news articles, developed with Clean Architecture and BLoC state management."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State Management
  flutter_bloc: ^8.1.6

  # Dependency Injection
  get_it: ^7.7.0

  # Data Handling
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Local Storage
  shared_preferences: ^2.2.3

  # Networking
  dio: ^5.4.3+1

  # Logging
  logger: ^2.3.0

  # Routing
  auto_route: ^7.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code Generation
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.9

  # Testing
  mockito: ^5.4.4

flutter:
  uses-material-design: true